cac_python/urls.py
from django.contrib import admin 
from django.urls import path ,include
from .views import LandingPage
from .views import RegistroPage
from .views import LoginPage
from .views import ComicPage1
from .views import ComicPage2
from .views import ComicPage3
from .views import ComicPage4
from .views import ComicPage5
from .views import ComicPage6
from .views import LibroPage1
from .views import LibroPage2
from .views import LibroPage3
from .views import LibroPage4
from .views import LibroPage5
from .views import LibroPage6
from .views import LibroPage7
from .views import LibroPage8
from .views import LibroPage9
from .views import LibroPage10
from .views import ModoCreador
from .views import index1



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",LandingPage.as_view(),name="index"),
    path("ModoCreador/",ModoCreador.as_view(),name="ModoCreador"),
    path("Registro/",RegistroPage.as_view(),name="Registro"),
    path("Login/",LoginPage.as_view(),name="Login"),
    path("Libro/",LibroPage1.as_view(),name="Libro1"),
    path("Libro2/",LibroPage2.as_view(),name="Libro2"),
    path("Libro3/",LibroPage3.as_view(),name="Libro3"),
    path("Libro4/",LibroPage4.as_view(),name="Libro4"),
    path("Libro5/",LibroPage5.as_view(),name="Libro5"),
    path("Libro6/",LibroPage6.as_view(),name="Libro6"),
    path("Libro7/",LibroPage7.as_view(),name="Libro7"),
    path("Libro8/",LibroPage8.as_view(),name="Libro8"),
    path("Libro9/",LibroPage9.as_view(),name="Libro9"),
    path("Libro10/",LibroPage10.as_view(),name="Libro10"),
    path("Comic1/",ComicPage1.as_view(),name="Comic1"),
    path("Comic2/",ComicPage2.as_view(),name="Comic2"),
    path("Comic3/",ComicPage3.as_view(),name="Comic3"),
    path("Comic4/",ComicPage4.as_view(),name="Comic4"),
    path("Comic5/",ComicPage5.as_view(),name="Comic5"),
    path("Comic6/",ComicPage6.as_view(),name="Comic6"),
    path("index1/",index1.as_view(),name="index1"),
    path("Creador/",include("creador_app.urls"))
]

creador_app/urls.py
from django.shortcuts import render

from django.contrib import admin
from django.urls import path , include


from .views import      CreadorListView   \
                    ,   CreadorDetailView \
                    ,   CreadorCreateView \
                    ,   CreadorUpdateView \
                    ,   CreadorDeleteView

app_name = "creador"

urlpatterns = [
    path("", CreadorListView.as_view(), name="all"),
    path("create/", CreadorCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", CreadorDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", CreadorUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", CreadorDeleteView.as_view(), name="delete")

]

creador_app/models.py
from django.db import models
from django.db.models import Model

# Create your models here.
class Creador(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model

    """
    nombre  =  models.CharField(max_length=400, null = False)
    autor  =  models.CharField(max_length=40, default="Anonimo")
    descripcion  =  models.CharField(max_length=1000)
    creacion = models.DateField(max_length=150,auto_now=True)
    rating  = models.PositiveSmallIntegerField(blank=False,null=False)
    abv     = models.FloatField(blank=True, null=True)

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
        db_table = "creador_meta"


    def __str__(self):
        return f"El Creador: {self.nombre}, Rating {self.abv}"

    def get_fields(self):
        """
         Obtiene los nombres y valores de los campos de un modelo.

        Retorna una lista de tuplas donde cada tupla contiene el nombre descriptivo del campo
        y el valor correspondiente para el objeto actual.

        :return: Lista de tuplas (nombre del campo, valor del campo)
        :rtype: list
        """
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

cac_python/views.py
from django.views.generic import TemplateView

class LandingPage (TemplateView):
    template_name = "index.html"

class RegistroPage (TemplateView):
    template_name = "Registro.html"

class LoginPage (TemplateView):
    template_name = "Login.html"

class LibroPage1 (TemplateView):
    template_name = "Libro1.html"

class LibroPage2 (TemplateView):
    template_name = "Libro2.html"

class LibroPage3 (TemplateView):
    template_name = "Libro3.html"

class LibroPage4 (TemplateView):
    template_name = "Libro4.html"

class LibroPage5 (TemplateView):
    template_name = "Libro5.html"

class LibroPage6 (TemplateView):
    template_name = "Libro6.html"

class LibroPage7 (TemplateView):
    template_name = "Libro7.html"

class LibroPage8 (TemplateView):
    template_name = "Libro8.html"

class LibroPage9 (TemplateView):
    template_name = "Libro9.html"

class LibroPage10 (TemplateView):
    template_name = "Libro10.html"
    
class ComicPage1 (TemplateView):
    template_name = "Comic1.html"

class ComicPage2 (TemplateView):
    template_name = "Comic2.html"

class ComicPage3 (TemplateView):
    template_name = "Comic3.html"

class ComicPage4 (TemplateView):
    template_name = "Comic4.html"

class ComicPage5 (TemplateView):
    template_name = "Comic5.html"

class ComicPage6 (TemplateView):
    template_name = "Comic6.html"

class ModoCreador (TemplateView):
    template_name = "ModoCreador.html"

class index1 (TemplateView):
    template_name = "index1.html"

creador_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Creador

# Create your views here.


class CreadorBaseView(View):
    template_name = 'Creador.html'
    model = Creador
    fields = '__all__'
    success_url = reverse_lazy('creador:all')


class CreadorListView(CreadorBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS Creador
    """

class CreadorDetailView(CreadorBaseView,DetailView):
    template_name = "Creador_detail.html"

class CreadorCreateView(CreadorBaseView,CreateView):
    template_name = "Creador_create.html"
    extra_context = {
        "tipo": "Crear Creador"
    }


class CreadorUpdateView(CreadorBaseView,UpdateView):
    template_name = "Creador_create.html"
    extra_context = {
        "tipo": "Actualizar Creador"
    }

class CreadorDeleteView(CreadorBaseView,DeleteView):
    template_name = "Creador_delete.html"
    extra_context = {
        "tipo": "Borrar Creador"
    }

creador_app/templates/Creador.html
{% load static %}
{% block content %}

<main>
  <!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static './css/style1.css' %}" />
  <title>Modo Creador</title>
</head>

<body>

  <header>
    <div class="logo">
      <img class="img" src="{% static './Assets/img/Logo 2.png' %}" width="60" height="54" alt="">
      <h1 class="slogan">Cafe y tinta</h1>
    </div>

    <nav role="search">
      <a class="link" href="{% url 'index' %}">Volver al inicio</a>
    </nav>
  </header>

  <main>
    <div class="Cuerpo">
      <br>
      <h2>Modo Creador</h2>
      <br>
      <h2 ><a class="link"href="{% url 'creador:create' %}">Crear un libro</a></h2>
      <br>
      <br>
      <div class="list">
        {% for creador in creador_list %}
          <legend>Nombre: {{creador.nombre}}</legend>
          <ul>
            <li>Autor : {{creador.autor}}</li>
            
          </ul>
  
            <div>
                <a href="{% url 'creador:detail' creador.id  %}">Saber mas</a>
            </div>
            <div>
                <a href="{% url 'creador:delete' creador.id %}">Borrar</a>
            </div>
            <div>
                <a href="{% url 'creador:update' creador.id %}">Editar</a>
            </div>
        <br>
        {% endfor %}
      </div>
      <br>
      <br>
      <br>
      <br>
    </div>
    
  </main>
  <footer>
    <nav role="search">
      <a class="link" href="">Home</a>
      <a class="link" href="">Contacto</a>
      <a class="link" href="">Productos</a>
    </nav>
  </footer>

</body>
{% endblock %}

creador_app/templates/Creador_create.html
{% load static %}
{% block content %}

<main>
  <!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static './css/style1.css' %}" />
  <title>Segunda Parte Django</title>
</head>

<body>

  <header>
    <div class="logo">
      <img class="img" src="{% static './Assets/img/Logo 2.png' %}" width="60" height="54" alt="">
      <h1 class="slogan">Cafe y tinta</h1>
    </div>

    <nav role="search">
      <a class="link" href="{% url 'creador:all' %}">Modo Creador</a>
      <a class="link" href="{% url 'index' %}">Volver al inicio</a>
    </nav>
  </header>


<main>
  <div class="Body_Create">
    <form method="post">
      {% csrf_token %}
      {{form.as_div}}
      <input type="submit" value="{{ tipo }}" />
    </form>
    <br>
    <a class= "link" href="{% url 'creador:all' %}">Volver al Inicio</a>
  </div>
</main>

<footer>
  <nav role="search">
    <a class="link" href="">Home</a>
    <a class="link" href="">Contacto</a>
    <a class="link" href="">Productos</a>
  </nav>
</footer>
{% endblock %}

creador_app/templates/Creador_delete.html
{% load static %}
{% block content %}

<main>
  <!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static './css/style1.css' %}" />
  <title>Segunda Parte Django</title>
</head>

<body>

  <header>
    <div class="logo">
      <img class="img" src="{% static './Assets/img/Logo 2.png' %}" width="60" height="54" alt="">
      <h1 class="slogan">Cafe y tinta</h1>
    </div>

    <nav role="search">
      <a class="link" href="{% url 'creador:all' %}">Modo Creador</a>
      <a class="link" href="{% url 'index' %}">Volver al inicio</a>
    </nav>
  </header>

<main>
  <div class="Body_Create">
    <h2>Estas seguro que deseas borrar este libro? Una vez borrado no podras recuperar</h2>
    <h2>" {{creador.nombre}} "</h2>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a class="link" href="{% url 'creador:all' %}">Cancelar</a>
  </div>
</main>
<footer>
  <nav role="search">
    <a class="link" href="">Home</a>
    <a class="link" href="">Contacto</a>
    <a class="link" href="">Productos</a>
  </nav>
</footer>
{% endblock %}

creador_app/templates/Creador_detail.html
{% load static %}
{% block content %}

<main>
  <!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static './css/style1.css' %}" />
  <title>Segunda Parte Django</title>
</head>

<body>

  <header>
    <div class="logo">
      <img class="img" src="{% static './Assets/img/Logo 2.png' %}" width="60" height="54" alt="">
      <h1 class="slogan">Cafe y tinta</h1>
    </div>

    <nav role="search">
      <a class="link" href="{% url 'creador:all' %}">Modo Creador</a>
      <a class="link" href="{% url 'index' %}">Volver al inicio</a>
    </nav>
  </header>

<body>


<main class="Body_Create">
  <div>
    <h1>{{creador.nombre}}</h1>
    {% for label, value in creador.get_fields %}
    <div>
      <span>{{label | upper}}</span>
      <span> <b> {{value}} </b></span>
    </div>

    {% endfor %}

    <br>
    <a class= "link" href="{% url 'creador:all' %}">Volver al Inicio</a>
  </div>
</main>

<footer>
  <nav role="search">
    <a class="link" href="">Home</a>
    <a class="link" href="">Contacto</a>
    <a class="link" href="">Productos</a>
  </nav>
</footer>
{% endblock %}

templates/Comic2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static './Css/Style-Comics.css' %}">
    <title>Cafe y Tinta</title>
</head>

<body>

    <div class= "grid-container">
        <div class="Header"> 
            <div class="logo">
                <img src="{% static './Assets/img/Logo 2.png' %}" alt="">
                <h2> Cafe y tinta</h2>
            </div>
            <nav class="Botones">
                <a href=""> Libros</a>
                <a href="">Comics</a>
                <a class="Registro" href="{% url 'index' %}"> Volver al inicio</a>
            </nav>
        </div>

        <div class="Main"> 
            
            <div class="Texto">
                <h2>Naruto</h2>
                <p>Autor: Masashi Kishimoto</p>
                <p>Año: 2000</p>
                <p>Sinopsis:  En la Villa Oculta de la Hoja, un chaval de lo más problemático que estudia en la escuela de ninjas, Naruto, se dedica a urdir gamberrada tras gamberrada.El sueño de Naruto es el de llegar un día a heredar el nombre de Hokage, reservado a los grandes héroes y de convertirse en el mejor ninja de todos los tiempos.¡¿Podrá Naruto llegar a cumplir sus anhelos de grandeza?!</p>
                <a href="">Descargar Aqui</a>
            </div>

            <div class="Imagen">
                <img src="{% static './Assets/img/C2.jpg' %}" alt="">
            </div>       
        </div>
       
       
        <div class="Footer">
            <nav class="BotonesFooter">
                <a href=""> Libros</a>
                <a href="">Comics</a>              
                <a class="Registro" href="{% url 'index' %}"> Volver</a>
            </nav>
        </div>
    </div>
</body>

</html>

templates/Comic5.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static './Css/Style-Comics.css' %}">
    <title>Cafe y Tinta</title>
</head>

<body>

    <div class= "grid-container">
        <div class="Header"> 
            <div class="logo">
                <img src="{% static './Assets/img/Logo 2.png' %}" alt="">
                <h2> Cafe y tinta</h2>
            </div>
            <nav class="Botones">
                <a href=""> Libros</a>
                <a href="">Comics</a>
                <a class="Registro" href="{% url 'index' %}"> Volver al inicio</a>
            </nav>
        </div>

        <div class="Main"> 
            
            <div class="Texto">
                <h2>Dragon Ball</h2>
                <p>Autor: Akira Toriyama</p>
                <p>Año: 1984</p>
                <p>Sinopsis:  Dragon ball nos cuenta las aventuras de Gokū, un guerrero saiyajin, experto en artes marciales que en su infancia inicia sus viajes y aventuras en las que pone a prueba y mejora sus habilidades de pelea, enfrentando oponentes y protegiendo a la Tierra de otros seres que quieren conquistarla y exterminar a la humanidad.</p>
                <a href="">Descargar Aqui</a>
                <p>No te pierdas la proxima entrega de Dragon Ball!</p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/CYcrmsdZuyw?si=mwNtbp0Edo4hZ2ln" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>

            <div class="Imagen">
                <img src="{% static './Assets/img/C5.jpg' %}" alt="">
            </div>       
        </div>
       
       
        <div class="Footer">
            <nav class="BotonesFooter">
                <a href=""> Libros</a>
                <a href="">Comics</a>              
                <a class="Registro" href="{% url 'index' %}"> Volver</a>
            </nav>
        </div>
    </div>
</body>

</html>

templates/Comic6.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static './Css/Style-Comics.css' %}">
    <title>Cafe y Tinta</title>
</head>

<body>

    <div class= "grid-container">
        <div class="Header"> 
            <div class="logo">
                <img src="{% static './Assets/img/Logo 2.png' %}" alt="">
                <h2> Cafe y tinta</h2>
            </div>
            <nav class="Botones">
                <a href=""> Libros</a>
                <a href="">Comics</a>
                <a class="Registro" href="{% url 'index' %}"> Volver al inicio</a>
            </nav>
        </div>

        <div class="Main"> 
            
            <div class="Texto">
                <h2>One Piece</h2>
                <p>Autor:  Eiichirō Oda</p>
                <p>Año: 1997 </p>
                <p>Sinopsis:  One Piece narra la historia de un joven llamado Monkey D. Luffy, que inspirado por su amigo pirata Shanks, comienza un viaje para alcanzar su sueño, ser el Rey de los piratas, para lo cual deberá encontrar el tesoro One Piece dejado por el anterior rey de los piratas Gol D. Roger.</p>
                <a href="">Descargar Aqui</a>
                <p>¿Sabias que One Piece tiene un live action? Ver trailer aqui.</p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/JoO7TGG2Kms?si=Qhux-0Qe9GJQK0OF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>

            <div class="Imagen">
                <img src="{% static './Assets/img/C6.jpg' %}" alt="">
            </div>       
        </div>
       
       
        <div class="Footer">
            <nav class="BotonesFooter">
                <a href=""> Libros</a>
                <a href="">Comics</a>              
                <a class="Registro" href="{% url 'index' %}"> Volver</a>
            </nav>
        </div>
    </div>
</body>

</html>

templates/Libro1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static './Css/Style-libros.css' %}">
    <title>Cafe y Tinta</title>
</head>

<body>

    <div class= "grid-container">
        <div class="Header"> 
            <div class="logo">
                <img src="{% static './Assets/img/Logo 2.png' %}" alt="">
                <h2> Cafe y tinta</h2>
            </div>
            <nav class="Botones">
                <a href=""> Libros</a>
                <a href="">Comics</a>
                <a class="Registro" href="{% url 'index' %}"> Volver al Inicio </a>
            </nav>
        </div>

        <div class="Main"> 
            
            <div class="Texto">
                <h2>Dune</h2>
                <p>Autor: Frank Herbert</p>
                <p>Año: 1965</p>
                <p>Sinopsis: Dune relata la historia del planeta desértico Arrakis, única fuente de melange, la especia necesaria para el viaje interestelar y que además garantiza longevidad y poderes psíquicos. La administración de Arrakis es transferida por el emperador de la noble Casa de Harkonnen a la Casa Atreides. Los primeros no quieren abandonar sus privilegios, y a través de traiciones y sabotajes, destierran al joven duque Paul Atreides al duro entorno del planeta para que muera. Pero Paul podría resultar ser mucho más que un duque al que han usurpado su puesto... Su lucha se encuentra en el epicentro de un nexo de poderosas personas e importantes sucesos, y las repercusiones se dejarán sentir a través del Imperio.</p>
            </div>

            <div class="Imagen">
                <img src="{% static './Assets/img/1.webp' %}" alt="">
            </div>       
        </div>
        <div class= "pdf">
            <embed src="{% static './Assets/PDF/Dune - Frank Herbert.pdf' %}" type="application/pdf" width="50%" height="500px"/>
        </div>
       
       
        <div class="Footer">
            <nav class="BotonesFooter">
                <a href=""> Libros</a>
                <a href="">Comics</a>              
                <a class="Registro" href="{% url 'index' %}"> Volver</a>
            </nav>
        </div>
    </div>
</body>

</html>

templates/Libro10.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static './Css/Style-libros.css' %}">
    <title>Cafe y Tinta</title>
</head>

<body>

    <div class= "grid-container">
        <div class="Header"> 
            <div class="logo">
                <img src="{% static './Assets/img/Logo 2.png' %}" alt="">
                <h2> Cafe y tinta</h2>
            </div>
            <nav class="Botones">
                <a href=""> Libros</a>
                <a href="">Comics</a>
                <a class="Registro" href="{% url 'index' %}"> Volver al inicio</a>
            </nav>
        </div>

        <div class="Main"> 
            
            <div class="Texto">
                <h2>El ladrón del rayo</h2>
                <p>Autor: Rick Riordan</p>
                <p>Año: 2005</p>
                <p>Sinopsis: El ladrón del rayo es un libro escrito por Rick Riordan. Es el primer libro de la serie Percy Jackson y los dioses del Olimpo, que cuenta las aventuras de un chico actual de doce años, Percy Jackson, cuando descubre que es un semidiós; el hijo de una mortal, Sally Jackson, y del dios griego, Poseidón.</p>
                <p>Percy Jackson tendra pronto una adaptacion en disney plus!!1</p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/bzHMAXqFFvc?si=7E4PhRvwlGF3_IXc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>

            <div class="Imagen">
                <img src="{% static './Assets/img/10.webp' %}" alt="">
            </div>       
        </div>
        <div class= "pdf">
            <embed src="{% static './Assets/PDF/percy_jackson_y_los_dioses_del_olimpo_1_-_el_ladron_del_rayo_-_rick_riordan.pdf' %}" type="application/pdf" width="50%" height="500px"/>
        </div>
       
       
        <div class="Footer">
            <nav class="BotonesFooter">
                <a href=""> Libros</a>
                <a href="">Comics</a>              
                <a class="Registro" href="{% url 'index' %}"> Volver</a>
            </nav>
        </div>
    </div>
</body>

</html>

templates/Libro2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static './Css/Style-libros.css' %}">
    <title>Cafe y Tinta</title>
</head>

<body>

    <div class= "grid-container">
        <div class="Header"> 
            <div class="logo">
                <img src="{% static './Assets/img/Logo 2.png' %}" alt="">
                <h2> Cafe y tinta</h2>
            </div>
            <nav class="Botones">
                <a href=""> Libros</a>
                <a href="">Comics</a>
                <a class="Registro" href="{% url 'index' %}"> Volver al inicio</a>
            </nav>
        </div>

        <div class="Main"> 
            
            <div class="Texto">
                


                <h2>It (eso)</h2>
                <p>Autor: Stephen King</p>
                <p>Año: 1986</p>
                <p>Sinopsis: Varios niños de una pequeña ciudad del estado de Maine se alían para combatir a una entidad diabólica que adopta la forma de un payaso y desde hace mucho tiempo emerge cada 27 años para saciarse de sangre infantil.
                </p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/_oBZ_zTz0Nw?si=bt2DcdFU7yTPa5pr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>

            <div class="Imagen">
                <img src="{% static './Assets/img/2.jpg' %}" alt="">
            </div>       
        </div>
        <div class= "pdf">
            <embed src="{% static './Assets/PDF/It - Stephen King.pdf' %}" type="application/pdf" width="50%" height="500px"/>
        </div>
       
       
        <div class="Footer">
            <nav class="BotonesFooter">
                <a href=""> Libros</a>
                <a href="">Comics</a>              
                <a class="Registro" href="{% url 'index' %}"> Volver</a>
            </nav>
        </div>
    </div>
</body>

</html>